image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - npm -g config set user root
    - npm install -g firebase-tools
    - npm install -g @angular/cli
    - npm install
    - npm run build 
    - firebase use --token $FIREBASE_DEPLOY_KEY default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
